#!/bin/sh

TMPFILE=`mktemp /tmp/buildinfo-XXXXXX`
BUILD_USER=`whoami`
BUILD_HOST=`hostname -f`

cat > $TMPFILE <<EOF
/* build-info.h
 *
 * automatically generated by build-info.sh, do not change.
*/

#define BUILD_USER "$BUILD_USER"
#define BUILD_HOST "$BUILD_HOST"
#define BUILD_BY "$BUILD_USER@$BUILD_HOST"
EOF

diff -q $TMPFILE build-info.h >/dev/null 2>/dev/null
if [ $? -ne 0 ]; then
  echo "BUILD-INFO: new build-info.h produced ($TMPFILE)"
  mv $TMPFILE build-info.h
else
  echo "BUILD-INFO: build-info.h already up-to-date. ($TMPFILE)"
fi
