#!/bin/sh
#
# Copyright 2012 Codethink Limited

# get versions
HEAD=`git rev-parse HEAD`
VERS=`git describe --all --long | cut -f3 -d '-'`

# check for cleanliness of the repository
STATS=$(git status --porcelain)
SUFFIX=${STATS:+-dirty}
DIRTY=${STATS:+dirty}
TMPFILE=`mktemp /tmp/gitrev-XXXXXX`

if [ x"$DIRTY" = x"" ]; then
    DIRTY=clean
fi

cat > $TMPFILE <<EOF
/* git-rev.h
 *
 * automatically generated by git-rev.sh, do not change.
*/

#define GIT_HEAD "$HEAD"
#define GIT_VERSION "$VERS$SUFFIX"
#define GIT_DIRTY "$DIRTY"
EOF

diff -q $TMPFILE git-rev.h >/dev/null 2>/dev/null
if [ $? -ne 0 ]; then
  echo "GIT-REV: git revision updated, new git-rev.h produced ($TMPFILE)"
  mv $TMPFILE git-rev.h
else
  echo "GIT-REV: git-rev.h already up-to-date. ($TMPFILE)"
fi
